name: Step 2, Add a job

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  create_file:
    name: Create the file

    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-file.html
          path: output
  sendToSlack:
    name: Send to slack
    needs: create_file

    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      - uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: C06M28ZA5UM
          content: 'file content'
          file_type: 'html'
          file_name: 'output/my-file.html'
          title: 'title of file'
          initial_comment: 'post by slack-upload-file'